### PR TITLE
Locker: new tokenomics

### PR DESCRIPTION
**Pull request by alexanderem49**
As per voting results of new tokenomics [proposal](https://vote.alluo.com/#/proposal/0xd654f8fdac284cfd93cc51d1b3af646b539e2c366bbf190302a82dc81f337473), this PR implements changes requested by Alluo DAO.

### CODE REVIEW

**Comment by alexanderem49** [comment]
Needs enhancement

**Comment by alexanderem49** [comment]
CvxDistributor now stores funds in Booster Vault and now it is returning LP tokens instead of CVX tokens.

**Comment by alexanderem49** [comment]
the amount of conflicts in this branch is 💀

**Review by 0xtuytuy — APPROVED** [review]
LGTM

**Review by AliyaDav — APPROVED** [review]

**Pull request merged**
